{{- $deprecatedOption := .Values.trow.validatingWebhooks -}}
{{ if or .Values.trow.validation.enabled $deprecatedOption }}
{{- if semverCompare ">=1.16-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: admissionregistration.k8s.io/v1
{{- else -}}
apiVersion: admissionregistration.k8s.io/v1
{{- end }}
kind: ValidatingWebhookConfiguration
metadata:
  name: trow-validator
webhooks:
  - name: {{ .Values.trow.domain }}
    admissionReviewVersions:
      - v1beta1
    sideEffects: None
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - pods
    failurePolicy: Fail
    clientConfig:
      service:
        name: trow
        path: "/validate-image"
        namespace: {{ .Release.Namespace }}
{{ end }}
