apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: trow-validator
webhooks:
  - name: validator.trow.io
    sideEffects: None
    admissionReviewVersions: ["v1", "v1beta1"]
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - pods
    failurePolicy: Fail
    clientConfig:
      caBundle: {{cabundle}}
      service:
        name: trow
        namespace: {{namespace}}
        path: "/validate-image"
